version: "3"
networks:
  internal-net:
    driver: bridge

services:
  api:
    networks:
      - internal-net
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: challengeDB
    volumes:
      - .:/usr/src/app
  db:
    container_name: sqldb
    networks:
      - internal-net
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challengeDB
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql